INSERT INTO `TB_IMAGEM` (`CO_IMAGEM`, `DS_CAMINHO`) VALUES
(1, 'LEONARDO-M-C-BESSA-56E8920C23AB6.JPG');

INSERT INTO `TB_CONTATO` (`CO_CONTATO`, `NU_TEL1`, `NU_TEL2`, `NU_TEL3`, `DS_EMAIL`) VALUES
(1, '61993274991', '6130826060', NULL, 'LEONARDOMCBESSA@GMAIL.COM');

INSERT INTO `TB_ENDERECO` (`CO_ENDERECO`, `DS_ENDERECO`, `DS_COMPLEMENTO`, `DS_BAIRRO`, `NU_CEP`, `NO_CIDADE`, `SG_UF`) VALUES
(1, 'QR 403 CONJUNTO 10 CASA 28', NULL, 'SAMAMBAIA NORTE', '72319111', 'BRASÍLIA', 'DF');

INSERT INTO `TB_PESSOA` (`CO_PESSOA`, `NU_CPF`, `NO_PESSOA`, `NU_RG`, `DT_CADASTRO`, `DT_NASCIMENTO`, `ST_SEXO`, `CO_ENDERECO`, `CO_CONTATO`) VALUES
(1, '72681438187', 'LEONARDO MACHADO CARVALHO BESSA', '2077811', '2016-10-31 00:00:00', '1984-07-06', 'M', 1, 1);

INSERT INTO `TB_FUNCIONALIDADE` (`CO_FUNCIONALIDADE`, `NO_FUNCIONALIDADE`, `DS_ROTA`, `ST_STATUS`) VALUES
(1, 'PERFIL MASTER', 'ADMIN/INDEX/SUPERPERFIL', 'A'),
(2, 'AUDITORIA LISTAR', 'ADMIN/AUDITORIA/LISTARAUDITORIA', 'A'),
(3, 'AUDITORIA DETALHAR', 'ADMIN/AUDITORIA/DETALHARAUDITORIA', 'A'),
(4, 'USUARIO CADASTRAR', 'ADMIN/USUARIO/CADASTROUSUARIO', 'A'),
(5, 'USUARIO LISTAR', 'ADMIN/USUARIO/LISTARUSUARIO', 'A'),
(6, 'MEU USUARIO', 'ADMIN/USUARIO/MEUPERFILUSUARIO', 'A'),
(7, 'PERFIL LISTAR', 'ADMIN/PERFIL/LISTARPERFIL', 'A'),
(8, 'PERFIL CADASTRAR', 'ADMIN/PERFIL/CADASTROPERFIL', 'A'),
(9, 'FUNCIONALIDADE LISTAR', 'ADMIN/FUNCIONALIDADE/LISTARFUNCIONALIDADE', 'A'),
(10, 'FUNCIONALIDADE CADASTRAR', 'ADMIN/FUNCIONALIDADE/CADASTROFUNCIONALIDADE', 'A'),
(11, 'FUNCIONALIDADES PERFIL', 'ADMIN/FUNCIONALIDADE/FUNCIONALIDADESPERFIL', 'A');


INSERT INTO `TB_PERFIL` (`CO_PERFIL`, `NO_PERFIL`, `ST_STATUS`) VALUES
(1, 'MASTER', 'A'),
(2, 'COORDENADOR', 'A'),
(3, 'MEMBRO', 'A');

INSERT INTO `TB_PERFIL_FUNCIONALIDADE` (`CO_PERFIL_FUNCIONALIDADE`, `CO_PERFIL`, `CO_FUNCIONALIDADE`) VALUES
(1, 1, 1),
(2, 2, 5),
(3, 2, 6),
(4, 3, 6);

INSERT INTO `TB_TIPO_PAGAMENTO` (`CO_TIPO_PAGAMENTO`, `DS_TIPO_PAGAMENTO`, `SG_TIPO_PAGAMENTO`) VALUES
(1, 'DINHEIRO', 'DI'),
(2, 'CARTÃO DE CRÉDITO', 'CC');

INSERT INTO `TB_USUARIO` (`CO_USUARIO`, `DS_SENHA`, `DS_CODE`, `ST_STATUS`, `DT_CADASTRO`, `CO_IMAGEM`, `CO_PESSOA`) VALUES
(1, '123456**', 'TVRJEK5EVTJLAW89', 'A', '2016-10-31 00:00:00', 1, 1);

INSERT INTO `TB_USUARIO_PERFIL` (`CO_USUARIO_PERFIL`, `CO_USUARIO`, `CO_PERFIL`) VALUES
(1, 1, 1);